---
apiVersion: v1
kind: Service
metadata:
  name: alarmprovider
  namespace: openwhisk
  labels:
    name: alarmprovider
spec:
  selector:
    name: alarmprovider
  ports:
    - port: 8080
      targetPort: 8090
      name: alarmprovider
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alarmprovider
  namespace: openwhisk
  labels:
    name: alarmprovider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: alarmprovider
    spec:
      restartPolicy: Always

      containers:
      - name: alarmprovider
        imagePullPolicy: IfNotPresent
        # custom alarm provider image. Not sure what we want to do with this.
        image: daisyycguo/alarmprovider
        ports:
        - name: alarmprovider
          containerPort: 8080
        env:
        - name: "DB_PROTOCOL"
          value: http
        - name: "DB_HOST"
          value: "couchdb.openwhisk:5984"
        - name: "DB_USERNAME"
          value: "whisk_admin"
        - name: "DB_PASSWORD"
          value: "some_passw0rd"
        - name: "ROUTER_HOST"
          value: "nginx.openwhisk"
        - name: "ENDPOINT_AUTH"
          value: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"

