apiVersion: batch/v1
kind: Job
metadata:
  name: install-catalog
  namespace: openwhisk
spec:
#  activeDeadlineSeconds: 600
  template:
    metadata:
      name: install-catalog
    spec:
      containers:
      - name: catalog
        image: openwhisk/kube-openwhisk-catalog
        env:
          - name: "WHISK_CLI_VERSION"
            value: "latest"
          - name: "WHISK_AUTH"
            value: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
          - name: "WHISK_API_HOST_NAME"
            value: "nginx.openwhisk"
      restartPolicy: Never
