apiVersion: batch/v1
kind: Job
metadata:
  name: alarmpkginstaller
  namespace: openwhisk
  labels:
    name: alarmpkginstaller
spec:
  template:
    metadata:
      labels:
        name: alarmpkginstaller
    spec:
      restartPolicy: Never
      containers:
      - name: alarmpkginstaller
        imagePullPolicy: IfNotPresent 
        image: daisyycguo/alarmpkginstaller:0.8
        env:
        - name: "APIHOST_URL"
          value: "nginx.openwhisk"
        - name: "DB_URL"
          value: "http://whisk_admin:some_passw0rd@couchdb.openwhisk:5984"
        - name: "DB_PREFIX"
          value: "alarm"
        - name: "APIHOST"
          value: "nginx.openwhisk"
        - name: "AUTH"
          value: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
