---
apiVersion: v1
kind: Service
metadata:
  name: kafkaprovider
  namespace: openwhisk
  labels:
    name: kafkaprovider
spec:
  selector:
    name: kafkaprovider
  ports:
    - port: 5000
      targetPort: 8091
      name: kafkaprovider
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkaprovider
  namespace: openwhisk
  labels:
    name: kafkaprovider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafkaprovider
    spec:
      restartPolicy: Always

      containers:
      - name: kafkaprovider
        imagePullPolicy: IfNotPresent
        # custom alarm provider image. Not sure what we want to do with this.
        image: openwhisk/kafkaprovider
        ports:
        - name: kafkaprovider
          containerPort: 8080
        env:
        - name: "DB_URL"
          value: "http://couchdb.openwhisk:5984"
        - name: "DB_USER"
          value: "whisk_admin"
        - name: "DB_PASS"
          value: "some_passw0rd"
        - name: "DB_PREFIX"
          value: "mq_prefix"
        - name: "LOCAL_DEV"
          value: "true"
        - name: "ROUTER_HOST"
          value: "nginx.openwhisk"
        - name: "ENDPOINT_AUTH"
          value: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"

